# Generated by Django 3.2.5 on 2021-12-11 09:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20211209_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Унікальне ID для цієї книги', primary_key=True, serialize=False),
        ),
    ]
